services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017     
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # storage:
  #   image: redis
  #   volumes:
  #     - ./service_counter/data:/data
  # counter:
  #   image: 14101916/redis_counter:v1.0.0
  #   environment:
  #     - PORT=3003
  #     - REDIS_URL=redis://storage
  #   ports:
  #     - 3003:3003
  #   depends_on:
  #     - storage        
  service_advert:
    image: 14101916/service_advert:v5.0.0
    environment:
      - PORT=3002
      # - COUNTER_URL=http://counter:3003
    ports:
      - 80:3002
    depends_on:
      - mongo
      # - counter
